#Configuração do sistema
#Tue Jul 01 06:57:57 GMT-03:00 2025
LinhasComErro_BDBR_Prelim=
LinhasComErro_BDDF_Prelim=
Tema_desktop=Default
Tema_table=Default
last_file_open=C\:\\Users\\Z D K\\OneDrive\\Documentos\\NetBeansProjects\\ByInews\\exportacoes\\Produtos\\BDBR\\Prelim.csv
