/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import framework.Log;
import java.io.File;
import javax.swing.JInternalFrame;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author Z D K
 */
public class Debug extends javax.swing.JFrame {

    jInternal_console console = jInternal_console.getInstance();

    /**
     * Creates new form Debug
     *
     * @param principal
     */
    public Debug(Principal principal) {
        initComponents(); 

        console.setSize(jDesktopPane1.getSize());
        jDesktopPane1.add(console);

        console.setVisible(true);

        Timer timer = new Timer(1000, e -> {
            new SwingWorker<Void, Void>() {

                String memoria, fileInstance, fileBackup, lastFileName, jInternal, frameTabela, lauda, internals, posicao;
                JInternalFrame[] frames = principal.Desktop.getAllFrames();
                int count = frames.length;


                @Override
                protected Void doInBackground() {
                    memoria = principal.controller.memoria_app();
                    fileInstance = (principal.controller.tabela == null) ? "No file" : principal.controller.tabela.file.getName();
                    fileBackup = (principal.controller.backup_file == null) ? "No file" : principal.controller.backup_file.getName();
                    File lastFile = new File(principal.controller.config.get("last_file_open"));
                    lastFileName = lastFile.getName();
                    jInternal = String.valueOf(principal.controller.jInternal);
                    frameTabela = (principal.controller.tabela == null) ? "Nulo" : "Instânciado";
                    lauda = (principal.controller.tabela == null) ? "Nulo" : principal.controller.tabela.controller.lauda.toString_to();
                    internals = "Quantidade de JInternalFrames abertos: " + count;
                    posicao = (principal.controller.posicao == null) ? "Nulo" : principal.controller.posicao;
                    return null;
                }

                @Override
                protected void done() {
                    // ✅ Atualizações visuais no EDT — com segurança
                    if (lbl_memoria != null) {
                        lbl_memoria.setText("Memória usada: " + memoria);
                    }
                    if (lbl_file_instance != null) {
                        lbl_file_instance.setText("File instance: " + fileInstance);
                    }
                    if (lbl_file_backup != null) {
                        lbl_file_backup.setText("File backup: " + fileBackup);

                    }
                    if (lbl_last_file != null) {
                        lbl_last_file.setText("Last file open: " + lastFileName);
                    }
                    if (lbl_jInternal != null) {
                        lbl_jInternal.setText("jInternal: " + jInternal);
                    }
                    if (lbl_frame_tabela != null) {
                        lbl_frame_tabela.setText("Frame tabela: " + frameTabela);
                    }
                    if (lbl_lauda != null) {
                        lbl_lauda.setText("Lauda: " + lauda);
                    }
                    
                    if(lbl_internal_frames != null){
                        lbl_internal_frames.setText(internals);
                    }
                    
                    if(lbl_posicao != null){
                        lbl_posicao.setText("Posição:" + posicao);
                    }

                    Log.memory_log("Memória usada ", memoria);
                }

            }.execute();
        });

        timer.setInitialDelay(1000); // começa após 1 segundo
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pb_debug = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_jInternal = new javax.swing.JLabel();
        lbl_last_file = new javax.swing.JLabel();
        lbl_memoria = new javax.swing.JLabel();
        lbl_file_backup = new javax.swing.JLabel();
        lbl_file_instance = new javax.swing.JLabel();
        lbl_internal_frames = new javax.swing.JLabel();
        lbl_frame_tabela = new javax.swing.JLabel();
        lbl_posicao = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_lauda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEBUG");
        setMinimumSize(new java.awt.Dimension(850, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEBUG");

        lbl_jInternal.setText("jInternal: ");

        lbl_last_file.setText("Last file open:");

        lbl_memoria.setText("Memória");

        lbl_file_backup.setText("File backup:");

        lbl_file_instance.setText("File instance: ");

        lbl_internal_frames.setText("Frames jInternals");

        lbl_frame_tabela.setText("Frame tabela:");

        lbl_posicao.setText("Posição:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_internal_frames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_file_instance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_file_backup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_jInternal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_last_file, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_posicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(lbl_frame_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_posicao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_file_instance)
                .addGap(20, 20, 20)
                .addComponent(lbl_file_backup)
                .addGap(20, 20, 20)
                .addComponent(lbl_last_file)
                .addGap(20, 20, 20)
                .addComponent(lbl_jInternal)
                .addGap(20, 20, 20)
                .addComponent(lbl_internal_frames)
                .addGap(20, 20, 20)
                .addComponent(lbl_frame_tabela)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        lbl_lauda.setText("Lauda:");

        javax.swing.GroupLayout pb_debugLayout = new javax.swing.GroupLayout(pb_debug);
        pb_debug.setLayout(pb_debugLayout);
        pb_debugLayout.setHorizontalGroup(
            pb_debugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_debugLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pb_debugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pb_debugLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1)
                        .addGap(0, 479, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pb_debugLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_lauda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pb_debugLayout.setVerticalGroup(
            pb_debugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pb_debugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbl_lauda)
                .addGap(20, 20, 20)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pb_debug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pb_debug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jDesktopPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentResized
        // TODO add your handling code here:
        console.setSize(jDesktopPane1.getSize());
    }//GEN-LAST:event_jDesktopPane1ComponentResized

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_file_backup;
    public javax.swing.JLabel lbl_file_instance;
    public javax.swing.JLabel lbl_frame_tabela;
    private javax.swing.JLabel lbl_internal_frames;
    public javax.swing.JLabel lbl_jInternal;
    public javax.swing.JLabel lbl_last_file;
    public javax.swing.JLabel lbl_lauda;
    public javax.swing.JLabel lbl_memoria;
    private javax.swing.JLabel lbl_posicao;
    private javax.swing.JPanel pb_debug;
    // End of variables declaration//GEN-END:variables
}
