/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexao.ConexaoAtiva;
import conexao.NetUtils;
import framework.Funcoes;
import framework.Image_panel;
import framework.Log;
import controller.C_principal;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.File;
import java.text.ParseException;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.text.MaskFormatter;
import model.Tema;

/**
 *
 * @author Z D K
 */
public class Principal extends javax.swing.JFrame {

    public C_principal controller;
    public AtomicBoolean action_frame = new AtomicBoolean(true);
    public AtomicBoolean operador_input = new AtomicBoolean(true);
    Debug d = new Debug(this);

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        controller = new C_principal(this);
        controller.init_controller();
        init_frame();
    }

    void init_frame() {
        pn_superior_desktop.setVisible(false);
        Desktop.setVisible(false);
        pn_inferior_1.setVisible(false);
        pn_inferior_2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        pn_frame = new javax.swing.JPanel();
        pn_lateral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_produto = new javax.swing.JTree();
        pn_desktop = new Image_panel("/icon/logo_globinho.png");
        pn_superior_desktop = new javax.swing.JPanel();
        lbl_close_frame = new javax.swing.JLabel();
        lbl_arquivo = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        pn_inferior_1 = new javax.swing.JPanel();
        lbl_in_jornal = new javax.swing.JLabel();
        lbl_tempo_producao = new javax.swing.JLabel();
        lbl_tempo_producao_tempo = new javax.swing.JLabel();
        lbl_in_jornal_tempo = new javax.swing.JLabel();
        lbl_saida_jornal = new javax.swing.JLabel();
        lbl_saida_jornal_tempo = new javax.swing.JLabel();
        pn_inferior_2 = new javax.swing.JPanel();
        try {
            MaskFormatter mf = new MaskFormatter("##:##:##");
            mf.setPlaceholderCharacter('0');
            mf.setAllowsInvalid(false);
            lbl_out_jornal_tempo = new javax.swing.JFormattedTextField(mf);
            lbl_out_jornal = new javax.swing.JLabel();
            lbl_stts_jornal = new javax.swing.JLabel();
            lbl_stts_jornal_tempo = new javax.swing.JLabel();
            lbl_horario = new javax.swing.JLabel();
            lbl_close_pn_lateral = new javax.swing.JLabel();
            jMenuBar2 = new javax.swing.JMenuBar();
            jMenu4 = new javax.swing.JMenu();
            jMenu5 = new javax.swing.JMenu();
            jMenu6 = new javax.swing.JMenu();
            menu_tema_star_light = new javax.swing.JMenuItem();
            menu_tema_default = new javax.swing.JMenuItem();
            menu_tema_dark = new javax.swing.JMenuItem();
            jMenu9 = new javax.swing.JMenu();
            mn_coluna_style = new javax.swing.JMenuItem();
            jMenuItem2 = new javax.swing.JMenuItem();
            jMenuItem3 = new javax.swing.JMenuItem();
            jMenuItem1 = new javax.swing.JMenuItem();

            jMenu1.setText("File");
            jMenuBar1.add(jMenu1);

            jMenu2.setText("Edit");
            jMenuBar1.add(jMenu2);

            jMenu7.setText("File");
            jMenuBar3.add(jMenu7);

            jMenu8.setText("Edit");
            jMenuBar3.add(jMenu8);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Mirror Page");
            setMinimumSize(new java.awt.Dimension(800, 600));
            setPreferredSize(new java.awt.Dimension(1280, 720));
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowActivated(java.awt.event.WindowEvent evt) {
                    formWindowActivated(evt);
                }
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    formWindowClosed(evt);
                }
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    formWindowClosing(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            pn_frame.setBackground(new java.awt.Color(0, 0, 0));
            pn_frame.setName("pn_frame"); // NOI18N

            pn_lateral.setName("pn_lateral"); // NOI18N

            jScrollPane1.setBorder(null);

            tree_produto.setBorder(null);
            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Árvore");
            tree_produto.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            tree_produto.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tree_produtoMouseClicked(evt);
                }
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    tree_produtoMouseReleased(evt);
                }
            });
            jScrollPane1.setViewportView(tree_produto);
            jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane1.getVerticalScrollBar().setUnitIncrement(5); // valor em pixels

            jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
                @Override
                public void mouseWheelMoved(java.awt.event.MouseWheelEvent e) {
                    JScrollBar bar = jScrollPane1.getVerticalScrollBar();
                    int rotation = e.getWheelRotation();
                    int amount = e.getScrollAmount();
                    bar.setValue(bar.getValue() + rotation * amount * 3); // 3 = suavidade
                }
            });

            javax.swing.GroupLayout pn_lateralLayout = new javax.swing.GroupLayout(pn_lateral);
            pn_lateral.setLayout(pn_lateralLayout);
            pn_lateralLayout.setHorizontalGroup(
                pn_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lateralLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addContainerGap())
            );
            pn_lateralLayout.setVerticalGroup(
                pn_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lateralLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pn_desktop.setName("pn_desktop"); // NOI18N

            pn_superior_desktop.setName("pn_superior_desktop"); // NOI18N

            lbl_close_frame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            lbl_close_frame.setForeground(new java.awt.Color(255, 0, 0));
            lbl_close_frame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbl_close_frame.setText("X");
            lbl_close_frame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lbl_close_frame.setName("lbl_close"); // NOI18N
            lbl_close_frame.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lbl_close_frameMouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lbl_close_frameMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lbl_close_frameMouseExited(evt);
                }
            });

            lbl_arquivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbl_arquivo.setText("Arquivo aberto");
            lbl_arquivo.setName("lbl_file_open"); // NOI18N

            javax.swing.GroupLayout pn_superior_desktopLayout = new javax.swing.GroupLayout(pn_superior_desktop);
            pn_superior_desktop.setLayout(pn_superior_desktopLayout);
            pn_superior_desktopLayout.setHorizontalGroup(
                pn_superior_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_superior_desktopLayout.createSequentialGroup()
                    .addComponent(lbl_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_close_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            pn_superior_desktopLayout.setVerticalGroup(
                pn_superior_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_close_frame, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addComponent(lbl_arquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            Desktop.setName("Desktop"); // NOI18N
            Desktop.addComponentListener(new java.awt.event.ComponentAdapter() {
                public void componentResized(java.awt.event.ComponentEvent evt) {
                    DesktopComponentResized(evt);
                }
            });

            javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
            Desktop.setLayout(DesktopLayout);
            DesktopLayout.setHorizontalGroup(
                DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            DesktopLayout.setVerticalGroup(
                DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout pn_desktopLayout = new javax.swing.GroupLayout(pn_desktop);
            pn_desktop.setLayout(pn_desktopLayout);
            pn_desktopLayout.setHorizontalGroup(
                pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_superior_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
            );
            pn_desktopLayout.setVerticalGroup(
                pn_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_desktopLayout.createSequentialGroup()
                    .addComponent(pn_superior_desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Desktop))
            );

            pn_superior_desktop.getAccessibleContext().setAccessibleName("");

            pn_inferior_1.setName("pn_inferior_1"); // NOI18N

            lbl_in_jornal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            lbl_in_jornal.setText("Entrada do Jornal");

            lbl_tempo_producao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            lbl_tempo_producao.setText("Tempo de Produção");
            lbl_tempo_producao.setRequestFocusEnabled(false);

            lbl_tempo_producao_tempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbl_tempo_producao_tempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lbl_tempo_producao_tempo.setText("00:00:00");

            lbl_in_jornal_tempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbl_in_jornal_tempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbl_in_jornal_tempo.setText("00:00:00");

            lbl_saida_jornal.setText("Saída do Jornal");

            lbl_saida_jornal_tempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lbl_saida_jornal_tempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbl_saida_jornal_tempo.setText("00:00:00");

            javax.swing.GroupLayout pn_inferior_1Layout = new javax.swing.GroupLayout(pn_inferior_1);
            pn_inferior_1.setLayout(pn_inferior_1Layout);
            pn_inferior_1Layout.setHorizontalGroup(
                pn_inferior_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_inferior_1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbl_in_jornal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbl_in_jornal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                    .addComponent(lbl_tempo_producao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbl_tempo_producao_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                    .addComponent(lbl_saida_jornal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lbl_saida_jornal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16))
            );
            pn_inferior_1Layout.setVerticalGroup(
                pn_inferior_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_inferior_1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pn_inferior_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_tempo_producao_tempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(lbl_tempo_producao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_in_jornal_tempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_in_jornal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_saida_jornal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_saida_jornal_tempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            pn_inferior_2.setName("pn_inferior_2"); // NOI18N

        }catch(ParseException  e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na máscara: " + e.getMessage());
        }
        lbl_out_jornal_tempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbl_out_jornal_tempo.setText("00:00:00");
        lbl_out_jornal_tempo.setName("Field Encerramento"); // NOI18N
        lbl_out_jornal_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_out_jornal_tempoActionPerformed(evt);
            }
        });

        lbl_out_jornal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_out_jornal.setText("Encerramento");

        lbl_stts_jornal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_stts_jornal.setText("Status do Jornal");

        lbl_stts_jornal_tempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_stts_jornal_tempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_stts_jornal_tempo.setText("00:00:00");
        lbl_stts_jornal_tempo.setName("lbl_stts_jornal_tempo"); // NOI18N

        lbl_horario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_horario.setForeground(new java.awt.Color(0, 204, 0));
        lbl_horario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_horario.setText("Horário Atual");
        lbl_horario.setToolTipText("Horário de Brasília");
        lbl_horario.setName("lbl_horario"); // NOI18N
        lbl_horario.setOpaque(true);

        javax.swing.GroupLayout pn_inferior_2Layout = new javax.swing.GroupLayout(pn_inferior_2);
        pn_inferior_2.setLayout(pn_inferior_2Layout);
        pn_inferior_2Layout.setHorizontalGroup(
            pn_inferior_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_inferior_2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_out_jornal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_out_jornal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_stts_jornal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_stts_jornal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        pn_inferior_2Layout.setVerticalGroup(
            pn_inferior_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_inferior_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_inferior_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_out_jornal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_stts_jornal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_out_jornal_tempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lbl_stts_jornal_tempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_horario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbl_close_pn_lateral.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_close_pn_lateral.setForeground(new java.awt.Color(255, 0, 0));
        lbl_close_pn_lateral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close_pn_lateral.setText("<");
        lbl_close_pn_lateral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_close_pn_lateral.setOpaque(true);
        lbl_close_pn_lateral.setPreferredSize(new java.awt.Dimension(10, 18));
        lbl_close_pn_lateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_close_pn_lateralMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_close_pn_lateralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_close_pn_lateralMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_frameLayout = new javax.swing.GroupLayout(pn_frame);
        pn_frame.setLayout(pn_frameLayout);
        pn_frameLayout.setHorizontalGroup(
            pn_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_frameLayout.createSequentialGroup()
                .addComponent(pn_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_close_pn_lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_inferior_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_inferior_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_frameLayout.setVerticalGroup(
            pn_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_frameLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pn_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_frameLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pn_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(pn_inferior_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pn_inferior_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(lbl_close_pn_lateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu4.setText("Configurações");

        jMenu5.setText("Tema");

        jMenu6.setText("Tabela");

        menu_tema_star_light.setText("Star Light");
        menu_tema_star_light.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tema_star_lightActionPerformed(evt);
            }
        });
        jMenu6.add(menu_tema_star_light);

        jMenu5.add(jMenu6);

        menu_tema_default.setText("Default");
        menu_tema_default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tema_defaultActionPerformed(evt);
            }
        });
        jMenu5.add(menu_tema_default);

        menu_tema_dark.setText("Dark");
        menu_tema_dark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tema_darkActionPerformed(evt);
            }
        });
        jMenu5.add(menu_tema_dark);

        jMenu4.add(jMenu5);

        jMenu9.setText("Tabela");

        mn_coluna_style.setText("Coluna");
        mn_coluna_style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_coluna_styleActionPerformed(evt);
            }
        });
        jMenu9.add(mn_coluna_style);

        jMenu4.add(jMenu9);

        jMenuItem2.setText("Exportar configurações");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Show Debug");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem1.setText("Histórico - Laudas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_frame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_tema_defaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tema_defaultActionPerformed
        // TODO add your handling code here:
        Funcoes.stop_action_frame(this, () -> {
            controller.apply_tema("Default", tree_produto);
        }, () -> {
            repaint();
            controller.atualizarMenuTemas(menu_tema_default, controller.temasMenuItems);
        }, action_frame);

    }//GEN-LAST:event_menu_tema_defaultActionPerformed

    private void tree_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_produtoMouseClicked
        // TODO add your handling code here:
        controller.tree_click_arquivo();
    }//GEN-LAST:event_tree_produtoMouseClicked

    private void lbl_close_frameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_frameMouseClicked
        // TODO add your handling code here:
        boolean close_frame = Funcoes.message_confirm(null, "Deseja fechar Frame?", "Fechar");
        if (close_frame) {
            controller.click_close_frame(null);
        }

    }//GEN-LAST:event_lbl_close_frameMouseClicked

    private void DesktopComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesktopComponentResized
        // TODO add your handling code here:
        if (Desktop.isVisible()) {
            if (controller.tabela != null) {
                controller.tabela.setSize(Desktop.getSize());
            }
        }

    }//GEN-LAST:event_DesktopComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (controller.tabela != null) {
            System.out.println("CLOSE file - " + controller.tabela.file.getAbsolutePath());
            Funcoes.acao_save_backup(controller.tabela.inews, controller.tabela.file, controller.tabela.controller);
        }

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Log.registrarErro_noEx("Programa fechado com sucesso");
    }//GEN-LAST:event_formWindowClosed

    private void lbl_close_pn_lateralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_pn_lateralMouseClicked
        // TODO add your handling code here:
        if (pn_lateral.isVisible()) {
            pn_lateral.setVisible(false);
            lbl_close_pn_lateral.setText(">");
        } else {
            pn_lateral.setVisible(true);
            lbl_close_pn_lateral.setText("<");
        }

        if (controller.tabela != null) {
            controller.tabela.controller.close_pop_up();
            SwingUtilities.invokeLater(() -> {
                controller.tabela.controller.updatePopupSelecao(controller.tabela.inews);
            });
        }
    }//GEN-LAST:event_lbl_close_pn_lateralMouseClicked

    private void menu_tema_star_lightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tema_star_lightActionPerformed
        // TODO add your handling code here:
        Funcoes.stop_action_frame(this, () -> {
            controller.apply_tema("Star Light", tree_produto);
        }, () -> {
            repaint();
            controller.atualizarMenuTemas(menu_tema_star_light, controller.temasMenuItems);

        }, action_frame);
    }//GEN-LAST:event_menu_tema_star_lightActionPerformed

    private void lbl_close_frameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_frameMouseEntered
        // TODO add your handling code here:
        if (Tema.modo_tema.equals("Default")) {
            lbl_close_frame.setBackground(Tema.COLOR_DARK);
            lbl_close_frame.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } else if (Tema.modo_tema.equals("Dark")) {
            lbl_close_frame.setBackground(Tema.COLOR_DEFAULT);
            lbl_close_frame.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_lbl_close_frameMouseEntered

    private void lbl_close_frameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_frameMouseExited
        // TODO add your handling code here:
        if (Tema.modo_tema.equals("Default")) {
            lbl_close_frame.setBackground(Tema.COLOR_DEFAULT);
            lbl_close_frame.setCursor(Cursor.getDefaultCursor());
        } else if (Tema.modo_tema.equals("Dark")) {
            lbl_close_frame.setBackground(Tema.COLOR_DARK);
            lbl_close_frame.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_lbl_close_frameMouseExited

    private void lbl_close_pn_lateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_pn_lateralMouseEntered
        // TODO add your handling code here:
        if (Tema.modo_tema.equals("Default")) {
            lbl_close_pn_lateral.setBackground(new Color(230, 240, 250));
            lbl_close_pn_lateral.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } else if (Tema.modo_tema.equals("Dark")) {
            lbl_close_pn_lateral.setBackground(new Color(60, 60, 60));
            lbl_close_pn_lateral.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }


    }//GEN-LAST:event_lbl_close_pn_lateralMouseEntered

    private void lbl_close_pn_lateralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close_pn_lateralMouseExited
        // TODO add your handling code here:
        if (Tema.modo_tema.equals("Default")) {
            lbl_close_pn_lateral.setBackground(Tema.COLOR_DEFAULT);
            lbl_close_pn_lateral.setCursor(Cursor.getDefaultCursor());
        } else if (Tema.modo_tema.equals("Dark")) {
            lbl_close_pn_lateral.setBackground(Tema.COLOR_DARK);
            lbl_close_pn_lateral.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_lbl_close_pn_lateralMouseExited

    private void menu_tema_darkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tema_darkActionPerformed
        // TODO add your handling code here:
        Funcoes.stop_action_frame(this, () -> {
            controller.apply_tema("Dark", tree_produto);
        }, () -> {
            repaint();
            controller.atualizarMenuTemas(menu_tema_dark, controller.temasMenuItems);
        }, action_frame);
    }//GEN-LAST:event_menu_tema_darkActionPerformed

    private void lbl_out_jornal_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_out_jornal_tempoActionPerformed
        // TODO add your handling code here:
        controller.stts_jornal();
    }//GEN-LAST:event_lbl_out_jornal_tempoActionPerformed

    private void tree_produtoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_produtoMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            controller.show_popup_jtree(evt);
        }
    }//GEN-LAST:event_tree_produtoMouseReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        controller.config.exportarConfiguracaoOrganizada(new File("config_exportado.txt"));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void mn_coluna_styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_coluna_styleActionPerformed
        controller.refresh_collumn();
    }//GEN-LAST:event_mn_coluna_styleActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (!d.isVisible()) {
            d.setVisible(true);
        } else {
            d.toFront();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        controller.in_operador();
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_arquivo;
    private javax.swing.JLabel lbl_close_frame;
    public javax.swing.JLabel lbl_close_pn_lateral;
    public javax.swing.JLabel lbl_horario;
    private javax.swing.JLabel lbl_in_jornal;
    public javax.swing.JLabel lbl_in_jornal_tempo;
    private javax.swing.JLabel lbl_out_jornal;
    public javax.swing.JFormattedTextField lbl_out_jornal_tempo;
    private javax.swing.JLabel lbl_saida_jornal;
    public javax.swing.JLabel lbl_saida_jornal_tempo;
    private javax.swing.JLabel lbl_stts_jornal;
    public javax.swing.JLabel lbl_stts_jornal_tempo;
    private javax.swing.JLabel lbl_tempo_producao;
    public javax.swing.JLabel lbl_tempo_producao_tempo;
    public javax.swing.JMenuItem menu_tema_dark;
    public javax.swing.JMenuItem menu_tema_default;
    public javax.swing.JMenuItem menu_tema_star_light;
    public javax.swing.JMenuItem mn_coluna_style;
    private javax.swing.JPanel pn_desktop;
    public javax.swing.JPanel pn_frame;
    public javax.swing.JPanel pn_inferior_1;
    public javax.swing.JPanel pn_inferior_2;
    public javax.swing.JPanel pn_lateral;
    public javax.swing.JPanel pn_superior_desktop;
    public javax.swing.JTree tree_produto;
    // End of variables declaration//GEN-END:variables
}
