/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.C_tbl_news;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;

/**
 *
 * @author Z D K
 */
public class Tbl_news extends javax.swing.JInternalFrame {

    public List<String> info;
    boolean delete = true;

    /**
     * Creates new form tbl_news
     */
    public C_tbl_news controller;

    public Tbl_news() {
        controller = new C_tbl_news(this);
        initComponents();

        // Remove a barra de título, mas mantém a borda
        javax.swing.plaf.basic.BasicInternalFrameUI ui
                = (javax.swing.plaf.basic.BasicInternalFrameUI) getUI();
        ui.setNorthPane(null); // Remove a barra de título

        setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // Remove o comportamento de edição com clique
        tbl_news.setCellSelectionEnabled(true);
        tbl_news.setSurrendersFocusOnKeystroke(true);
        tbl_news.putClientProperty("JTable.autoStartsEdit", Boolean.FALSE);

// Define ação para iniciar edição ao pressionar Enter
        InputMap im = tbl_news.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am = tbl_news.getActionMap();

// Substitui a ação de Enter para iniciar a edição manualmente
        im.put(KeyStroke.getKeyStroke("ENTER"), "startEdit");
        am.put("startEdit", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = tbl_news.getSelectedRow();
                int col = tbl_news.getSelectedColumn();
                if (row >= 0 && col >= 0 && tbl_news.isCellEditable(row, col)) {
                    tbl_news.editCellAt(row, col);
                    tbl_news.requestFocusInWindow();
                    Component editor = tbl_news.getEditorComponent();
                    if (editor != null) {
                        editor.requestFocusInWindow();
                    }
                }
            }
        });

        tbl_news.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                controller.close_pop_up(); // Fecha popup ao começar nova seleção
            }
        });

        jScrollPane1.getViewport().setBackground(new Color(100, 100, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_news = new javax.swing.JTable();

        setBackground(new java.awt.Color(30, 30, 30));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tbl_news.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_news.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_newsMouseReleased(evt);
            }
        });
        tbl_news.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_newsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_newsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_news);

        javax.swing.GroupLayout pn_fundoLayout = new javax.swing.GroupLayout(pn_fundo);
        pn_fundo.setLayout(pn_fundoLayout);
        pn_fundoLayout.setHorizontalGroup(
            pn_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        pn_fundoLayout.setVerticalGroup(
            pn_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_newsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_newsKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_INSERT) {
            if (info.get(1).equals("Formato")) {
                return;
            }
            controller.add_linha_selected(tbl_news, pn_fundo);
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (info.get(1).equals("Formato")) {
                return;
            }

            if (tbl_news.getSelectedRow() == -1 || tbl_news.getSelectedRow() == 0 || tbl_news.getSelectedRow() == 1) {
                return;
            }
            
            if (!delete) {
                System.out.println("Aguarde para deletar novamente...");
                return;
            }

            delete = false;

            controller.excluir_linha(tbl_news, pn_fundo);

            // Timer para reabilitar a exclusão após 2 segundos
            javax.swing.Timer timer = new javax.swing.Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    delete = true;
                    System.out.println("Pode deletar novamente agora.");
                }
            });
            timer.setRepeats(false); // garante que só executa 1 vez
            timer.start();
            return;

        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            if (info.get(1).equals("Formato")) {
                return;
            }

            controller.in_celula(tbl_news);

        }

        if (evt.getKeyCode() == KeyEvent.VK_B) {
            info_variavel();
            System.out.println("Painel Fundo: " + pn_fundo.getHeight());

        }

        if (evt.isAltDown() && evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            // ALT + →
            if (info.get(1).equals("Formato")) {
                return;
            }
            controller.lauda.lauda(tbl_news, pn_fundo);
        }

        if (info.get(1).equals("Formato")) {
            JOptionPane.showMessageDialog(null, "Tabela não permite digitação!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_tbl_newsKeyPressed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        controller.ajustar_largura_colunas(tbl_news);
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbl_newsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_newsKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();

            controller.add_tempo_entrada(tbl_news);
            controller.in_tMat(tbl_news);

        }

    }//GEN-LAST:event_tbl_newsKeyReleased

    private void tbl_newsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_newsMouseReleased
        // TODO add your handling code here:
        controller.tempo_linhas_selecionadas(tbl_news);
    }//GEN-LAST:event_tbl_newsMouseReleased

    void info_variavel() {
        for (String infos : info) {
            System.out.println(infos);
        }

        controller.ver_lauda(tbl_news.getSelectedRow());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pn_fundo;
    public javax.swing.JTable tbl_news;
    // End of variables declaration//GEN-END:variables

}
